//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Zakaz_Tovar = new HashSet<Zakaz_Tovar>();
        }
    
        public int ID { get; set; }
        public int Nomer { get; set; }
        public System.DateTime DataZakaza { get; set; }
        public System.DateTime DataVidachi { get; set; }
        public int IDPunkt { get; set; }
        public decimal Summa { get; set; }
        public int IDPolzovatel { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Punkt Punkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz_Tovar> Zakaz_Tovar { get; set; }
    }
}
